# -*- coding: utf-8 -*-
"""1110.유성욱.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ztHv4e74ynqMnxpWvkdb4wtA5LOQFP2d

9월 7일 파이썬 리스트 연습 ( 1110유성욱 )

---
"""

str = "안녕하세요"

for index in str :
  print(index)

lst = [1,2,3,4,5,6,7,8,9,10]

for index in lst : 
  print(index)

xlst = range(10)
xlst
type(xlst)

xlst = list(xlst)
xlst
#type(xlst)

"""for문을 활용한 리스트 변경"""

xlst = ['1', '2', '3', '4', '5']

type(xlst)
print(xlst)

xlst = [int(item) for item in xlst]
print(xlst)

"""10개의 숫자를 입력 받아서 리스트에 저장하고 짝수와 홀수 리스트를 만드시오."""

# even = [] , odd = []

# for i in range(10) :
#   Num = int(input())
#   if (Num % 2 == 0):
#     even.append(Num)
#   else : 
#     odd.append(Num)

even = [] ; odd = []

for i in range(10):
   num = int(input('숫자입력 : '))

   if num % 2 == 0 :
     even.append(num)
   else :
      odd.append(num)

print(f'even={even}')
print(f'odd={odd}')

bloom = {'1월': '수선화', '3월': '프리지아','4월': '라일락','5월' , '장미','6월':'장미' , '7월': '무궁화' ,'11월', '국화'}

bloom

for k,v in bloom.items():
  if k == '1월':
    print(v)

for k,v in bloom.items():
  if v == '장미':
    print(k)

[k for k, v in bloom.items() if v == '장미']

typhoon = "6일 한반도를 강타한 제11호 태풍 ‘힌남노’는 기상청이 “이런 태풍은 처음”이라고 밝힐 정도로 이례적이었다. 태풍 규모가 컸을 뿐 아니라 한반도로 접근할수록 위력이 강해지면서 “역대 가장 강력한 태풍이 될 것”이라는 우려가 나왔다.하지만 뚜껑을 열어본 결과 불행 중 다행으로 기상청이 예고한 ‘역대급’ 태풍보다는 강도가 다소 약해졌다. 강력한 중심기압에 비해 상대적으로 풍속이 낮았다.6일 오전 4시 50분 태풍이 경남 거제 인근에 상륙했을 때 태풍의 중심기압은 955.9hPa(헥토파스칼)로 1959년 ‘사라’(951.5hPa), 2003년 ‘매미’(954.0hPa)에 이어 세 번째로 강력했다. 열대성 저기압인 태풍은 중심기압이 낮을수록 강하다.풍속은 이보다 낮은 역대 8위였다. 하루 최대풍속이 매미 수준(초속 51.1m·시속 184km)일 수 있다는 관측이 나왔었지만, 힌남노가 기록한 하루 최대풍속은 초속 37.2m(시속 134km)였다. 경남 통영 매물도에서 관측된 순간 최대풍속 43.1m(시속 155km) 역시 매미 기록(초속 60.0m·시속 216km)보다 낮았다.당초 전망이 다소 어긋난 이유는 한반도 북서쪽에서 내려온 차고 건조한 공기가 예상보다 일찍 힌남노에 유입됐기 때문이다. 태풍은 따뜻하고 습한 공기덩어리다. 차고 건조한 공기가 들어오면 그 힘이 약해진다.여기에 힌남노가 빠른 속도로 지나간 것이 영향을 미쳤을 수 있다. 일반적으로 태풍은 상륙 후 강도가 약해진다. 하지만 힌남노처럼 강한 태풍은 상륙 후에도 강도를 유지하면서 내륙의 지형지물과 부딪혀 순간적으로 더 강한 바람을 만들어내는 경우가 많다. 당초 힌남노는 한반도 상공에 3∼4시간 머무를 것으로 봤지만 실제로는 6일 오전 4시 50분 거제에 상륙한 뒤 7시 10분 울산으로 빠져나가며 2시간 20분 머물렀다. 태풍 동쪽에 있는 북태평양 고기압이 시계 방향으로 돌면서 북쪽으로 향하는 태풍을 더 빠르게 밀어 올렸기 때문이다."

typhoon = typhoon.replace("\n","")
word = input('찾는 단어를 넣어줘 :')

print(f'찾는 단어 {word}는 {typhoon.count(word)}번 나와')

sentence = typhoon.split(".")
for i in sentence : 
  print(i)