# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L1BVF8aORuDwl6aLIcNIAgjbjjPuzRwG
"""

from google.colab import drive
drive.mount('/content/gdrive')

fp = open('/content/gdrive/My Drive/지역평균기온.txt','r', encoding = 'utf=8')

fp

data = fp.readlines()
data

type(data)

data = fp.read()
data

fp.close()